### ISSUE TITLE
execute on freshly installed system from "step-by-step" guide

### ISSUE THREAD

**Issue by brenkem** [jprisab/labdoo_labtix#8]
After installing a system I wanted to install the recommended tools. But I could not find a example or option to simply install it.

I tried:
    sudo ./install_labdoo_contents_kiwix.sh -l english -d /home/labdoo -f 100000

But this failed because there is no "source contents" (what ever this means) on a new system.

Is there any option or script to simply install a list of education tools? Or does this script only belong to some wikis from a local drive?

**Comment by jprisab** [comment]
Hello,

yes, unfortunately it requires having downloaded first the kiwix contents to a local harddrive...
still, this functionallity has not been maintained due to the lack of usage (it required to update the contents under http://ftp.labdoo.org/download/install-disk/wiki-archive/kiwix/

what stopped being done around 2020...

still, depending on the size of the laptop you are restoring... I recommend to use the biggest available image 
(ie for english you have 4 different sizes available (260Gb, 120Gb, 80Gb,40Gb) you can choose from under http://ftp.labdoo.org/download/install-disk/EN_English_images/
the biggest one has more contents you could have installed using the script....

BR

**Comment by brenkem** [comment]
Hi,

after some research I found the desired scripts here:

http://ftp.labdoo.org/download/install-disk/installskripts/


Have fun. Case closed.
